# Generated by Django 3.0.8 on 2020-07-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song',
            field=models.CharField(default='mp3', max_length=250),
        ),
        migrations.AddField(
            model_name='song',
            name='type',
            field=models.CharField(default='mp3', max_length=900),
        ),
    ]
