# Generated by Django 3.0.8 on 2020-07-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20200709_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='addr',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
