# Generated by Django 3.0.8 on 2020-07-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='addr',
            field=models.CharField(default='https://irsv.upmusics.com/99/Shahab%20Mozaffari%20-%20Rade%20Pa%20(320).mp3', max_length=500),
        ),
    ]
