# Generated by Django 3.0.8 on 2020-07-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_comments_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='page',
            field=models.IntegerField(default=1),
        ),
    ]
