# Generated by Django 3.0.8 on 2020-07-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20200712_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='page',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
