# Generated by Django 3.0.8 on 2020-07-12 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20200712_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='page',
        ),
    ]
