# Generated by Django 3.0.8 on 2020-07-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20200712_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(default='', max_length=1000)),
                ('artist_image', models.ImageField(upload_to='')),
                ('artist_description', models.CharField(default='', max_length=2000)),
            ],
        ),
    ]
