# Generated by Django 3.0.8 on 2020-07-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_image',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
