# Generated by Django 3.0.8 on 2020-07-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_like_dislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_image',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
