# Generated by Django 3.0.8 on 2020-07-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_auto_20200718_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='like_dislike',
            name='page',
            field=models.IntegerField(default=1),
        ),
    ]
