# Generated by Django 3.0.8 on 2020-07-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_auto_20200718_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='likes',
            field=models.CharField(default='like', max_length=4),
        ),
    ]
