# Generated by Django 3.0.8 on 2020-07-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_auto_20200719_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislike',
            name='dislikes',
            field=models.CharField(default='dislike', max_length=7),
        ),
    ]
