# Generated by Django 3.0.8 on 2020-07-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='username', max_length=50)),
                ('email', models.CharField(default='email', max_length=220)),
                ('phone_number', models.IntegerField(default='091234567', max_length=13)),
                ('name', models.CharField(default='name', max_length=60)),
                ('passsword', models.CharField(default='password', max_length=300)),
            ],
        ),
    ]
