# Generated by Django 3.0.8 on 2020-07-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=100)),
                ('movie_rate', models.FloatField()),
                ('movie_length', models.CharField(max_length=100)),
                ('movie_genre', models.CharField(max_length=100)),
                ('movie_producer', models.CharField(max_length=100)),
                ('movie_actors', models.CharField(max_length=900)),
                ('movie_country', models.CharField(default='iran', max_length=100)),
                ('movie_year', models.IntegerField(default='1399')),
                ('movie_description', models.SlugField(max_length=2000)),
            ],
        ),
    ]
