# Generated by Django 3.0.8 on 2020-07-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_url',
            field=models.CharField(default='https://hw14.cdn.asset.aparat.com/aparat-video/8f16a9aa423481f45bf8f23dc5e17b1421199695-144p.mp4', max_length=1000),
        ),
    ]
